import { Search } from "lucide-react";

function FilterBar({ filters, categories, libraries, onChange }) {
  const update = (key, value) => onChange({ ...filters, [key]: value });

  return <section className="rounded-xl border border-[#F3E8C8] bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-4"><label className="flex items-center gap-3 rounded-xl border border-[#F3E8C8] bg-[#FFFDF7] px-4 py-3 focus-within:border-amber-400 focus-within:ring-2 focus-within:ring-amber-100"><Search size={19} className="text-amber-700" /><input value={filters.search} onChange={(event) => update("search", event.target.value)} type="search" placeholder="Search by title, author or ISBN" className="min-w-0 flex-1 bg-transparent text-sm text-[#1F2937] outline-none placeholder:text-gray-400" /></label><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label><span className="sr-only">Filter by category</span><select value={filters.category} onChange={(event) => update("category", event.target.value)} className="w-full rounded-lg border border-[#F3E8C8] bg-white px-3 py-2.5 text-sm text-gray-700 outline-none focus:border-amber-400"><option value="">All categories</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label><span className="sr-only">Filter by library</span><select value={filters.library} onChange={(event) => update("library", event.target.value)} className="w-full rounded-lg border border-[#F3E8C8] bg-white px-3 py-2.5 text-sm text-gray-700 outline-none focus:border-amber-400"><option value="">All libraries</option>{libraries.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label><label><span className="sr-only">Filter by availability</span><select value={filters.availability} onChange={(event) => update("availability", event.target.value)} className="w-full rounded-lg border border-[#F3E8C8] bg-white px-3 py-2.5 text-sm text-gray-700 outline-none focus:border-amber-400"><option value="all">All availability</option><option value="available">Available now</option><option value="unavailable">Unavailable</option></select></label><label><span className="sr-only">Sort books</span><select value={filters.sort} onChange={(event) => update("sort", event.target.value)} className="w-full rounded-lg border border-[#F3E8C8] bg-white px-3 py-2.5 text-sm text-gray-700 outline-none focus:border-amber-400"><option value="-createdAt">Newest first</option><option value="createdAt">Oldest first</option><option value="title">Title A–Z</option><option value="-availableCopies">Most available</option></select></label></div></div></section>;
}

export default FilterBar;
